version: 2.1
jobs:
    build:

        docker:
            - image: circleci/golang:1.11.3

        steps:
            - checkout

            - run:
                  name: Make Build And Dist Dir
                  command: |
                      mkdir dist
                      mkdir build

            - run:
                  name: Linux
                  command: |
                      mkdir build/linux
                      cp -r static build/linux
                      cp app.1.toml build/linux/app.toml
                      GOOS=linux go build -o build/linux/ooi4
                      openssl sha256 build/linux/ooi4 > build/linux/shasum.txt

            - run:
                  name: Darwin
                  command: |
                      mkdir build/darwin
                      cp -r static build/darwin
                      cp app.1.toml build/darwin/app.toml
                      GOOS=darwin go build -o build/darwin/ooi4
                      openssl sha256 build/darwin/ooi4 > build/darwin/shasum.txt

            - run:
                  name: Windows
                  command: |
                      mkdir build/windows
                      cp -r static build/windows
                      cp app.1.toml build/windows/app.toml
                      GOOS=windows go build -o build/windows/ooi4.exe
                      openssl sha256 build/windows/ooi4.exe > build/windows/shasum.txt

            - run:
                  name: Package
                  command: |
                      cd build
                      zip -v -r ../dist/ooi4-linux.zip linux
                      zip -v -r ../dist/ooi4-darwin.zip darwin
                      zip -v -r ../dist/ooi4-windows.zip windows

            - store_artifacts:
                  path: ./dist
