version: 2
jobs:
    build:
        
        docker:
            - image: circleci/golang:1.11.1
              
        parallelism: 4
        
        steps:
            - checkout
            
            - run:
                  name: Make Build Dir
                  command: mkdir build
            
            - run:
                  name: Linux
                  command: GOOS=linux go build -o build/ooi4-linux
                  
            - run:
                  name: Darwin
                  command: GOOS=darwin go build -o build/ooi4-darwin

            - run:
                  name: Windows
                  command: GOOS=windows go build -o build/ooi4-windows.exe
                  
            - store_artifacts:
                  path: ./build/ooi4-linux
                  
            - store_artifacts:
                  path: ./build/ooi4-darwin
                  
            - store_artifacts:
                  path: ./build/ooi4-windows.exe
